"""descriptions

Revision ID: 00d213cb60a8
Revises: f0ca65bbaa07
Create Date: 2017-01-15 19:11:57.570706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d213cb60a8'
down_revision = 'f0ca65bbaa07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audition_day', sa.Column('description', sa.String(length=4000), nullable=True))
    op.add_column('show', sa.Column('description', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'description')
    op.drop_column('audition_day', 'description')
    # ### end Alembic commands ###
