"""hidden

Revision ID: bbc04efdde74
Revises: fa531dd0615e
Create Date: 2017-01-18 00:32:57.994374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbc04efdde74'
down_revision = 'fa531dd0615e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('hidden', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'hidden')
    # ### end Alembic commands ###
