"""initial

Revision ID: f0ca65bbaa07
Revises: 
Create Date: 2017-01-15 01:29:12.966733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ca65bbaa07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audition_day',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('show_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('date', 'show_id')
    )
    op.create_table('show_managers',
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_provider',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('user_uid', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'provider_id')
    )
    op.create_table('audition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('audition_day_show_id', sa.Integer(), nullable=True),
    sa.Column('audition_day_date', sa.Date(), nullable=True),
    sa.Column('auditionee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['audition_day_show_id', 'audition_day_date'], ['audition_day.show_id', 'audition_day.date'], ),
    sa.ForeignKeyConstraint(['auditionee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('last_edit_time', sa.DateTime(), nullable=True),
    sa.Column('edits', sa.Integer(), nullable=True),
    sa.Column('comment_body', sa.String(length=2000), nullable=True),
    sa.Column('audition_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('viewable_by_auditionee', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['audition_id'], ['audition.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('audition')
    op.drop_table('user_provider')
    op.drop_table('show_managers')
    op.drop_table('audition_day')
    op.drop_table('user')
    op.drop_table('show')
    # ### end Alembic commands ###
