"""show_schedule

Revision ID: fa531dd0615e
Revises: 00d213cb60a8
Create Date: 2017-01-17 15:36:04.882175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa531dd0615e'
down_revision = '00d213cb60a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('schedule_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'schedule_public')
    # ### end Alembic commands ###
